### ISSUE TITLE
CSV Download -> not in Zip

### ISSUE THREAD

**Issue by jeremie-olivier** [thp-lab/intuition-graph#22]
While putting the 2 CSV file in a zip might apears to be a good idea, this trigger a browser security feature on chrome : ![Image](https://github.com/user-attachments/assets/9076038a-684f-4837-85a9-092cb9edc193)

So I think it's better to just trigger the download for the 2 CSV direclty ( without a zip file )

**Comment by ZealRa** [comment]
Chrome still has the warning message anyway. So I reviewed the PR and merged it into dev after testing.
