### ISSUE TITLE
Implement a modal to give details of the selected atom on the graph

### ISSUE THREAD

**Issue by ThibaultL24** [thp-lab/intuition-graph#9]
- [x] show triples where the atom is used as subject
- [x]  show triples where the atom is used as predicate 
- [x]  show triples where the atom is used as object
- [x]  show atom details
- [x] create a beautiful display instead of json display
- [x]  create function to display properly the atom vault
- [x]  show how many time the atom is used as subject, predicate, object
- [x]  show how much is stack on the atom and converted the result in eth or $ and not in wei
- [x]  show creator in the node details

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified GraphVisualization.js to add a function that displays triples where the clicked atom is used as subject, predicate, or object. Added a modal to show this information when a node is clicked.

You can review changes in this commit: https://github.com/mnmnk43434/THP-Lab-intuition-graph-9/commit/6551868ff0ca8f92629183c54fa2a0aea1a4f970.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
